#!/usr/bin/env python
"""Export Scope B runtime summary CSV, paper table, and bar figure."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt
import numpy as np


PLOT_STYLE = {
    "font.family": "Times New Roman",
    "font.size": 10,
    "axes.titlesize": 10,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "axes.linewidth": 0.8,
    "grid.linewidth": 0.4,
}
PLOT_SAVE_KWARGS = {"dpi": 300, "bbox_inches": "tight", "pad_inches": 0.02}

METHOD_ORDER = ["Base", "+gating", "+traj", "+adaptive"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build Scope B artifacts from runtime_profile_e2e.csv.")
    parser.add_argument(
        "--in-csv",
        type=Path,
        default=Path("results/main_val/runtime/runtime_profile_e2e.csv"),
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("results/main_val/runtime/runtime_profile_e2e_summary.csv"),
    )
    parser.add_argument(
        "--table-tex",
        type=Path,
        default=Path("paper/cea_draft/tables/runtime_scopeb.tex"),
    )
    parser.add_argument(
        "--fig-pdf",
        type=Path,
        default=Path("paper/cea_draft/figures/runtime_e2e_bar.pdf"),
    )
    return parser.parse_args()


def read_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Scope B runtime CSV not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_summary(path: Path, rows: List[Dict[str, str]]) -> List[Dict[str, str]]:
    mean_rows = [r for r in rows if r.get("row_type", "").strip().lower() == "mean"]
    row_map = {r["method"]: r for r in mean_rows}
    ordered = [row_map[m] for m in METHOD_ORDER if m in row_map]
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "method",
        "split",
        "warmup_iters",
        "repeat_runs",
        "total_frames",
        "fps_e2e",
        "fps_e2e_std",
        "mem_peak_mb_e2e",
        "mem_peak_mb_e2e_std",
        "cpu_norm_e2e",
        "cpu_norm_e2e_std",
        "decode_time",
        "decode_time_std",
        "detector_time",
        "detector_time_std",
        "tracking_time",
        "tracking_time_std",
        "write_time",
        "write_time_std",
        "detector_name",
        "input_resolution",
    ]
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for r in ordered:
            writer.writerow({k: r.get(k, "") for k in fields})
    return ordered


def write_table(path: Path, rows: List[Dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = [
        "% Auto-generated by scripts/export_scopeb_artifacts.py",
        r"\begin{tabular}{l S S S S S S}",
        r"\toprule",
        r"Method & {FPS$_{\mathrm{e2e}}$} & {Mem$_{\mathrm{peak}}$ (MB)} & {CPU$_{\mathrm{norm}}$} & {Decode (s)} & {Detector (s)} & {Track+Write (s)} \\",
        r"\midrule",
    ]
    for r in rows:
        trk_write = float(r["tracking_time"]) + float(r["write_time"])
        fps = f"{float(r['fps_e2e']):.3f}({int(round(float(r['fps_e2e_std']) * 1000))})"
        mem = f"{float(r['mem_peak_mb_e2e']):.3f}({int(round(float(r['mem_peak_mb_e2e_std']) * 1000))})"
        cpu = f"{float(r['cpu_norm_e2e']):.3f}({int(round(float(r['cpu_norm_e2e_std']) * 1000))})"
        lines.append(
            " & ".join(
                [
                    r["method"],
                    fps,
                    mem,
                    cpu,
                    f"{float(r['decode_time']):.3f}",
                    f"{float(r['detector_time']):.3f}",
                    f"{trk_write:.3f}",
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def write_figure(path: Path, rows: List[Dict[str, str]]) -> None:
    plt.rcParams.update(PLOT_STYLE)
    methods = [r["method"] for r in rows]
    x = np.arange(len(methods), dtype=float)
    fps = np.asarray([float(r["fps_e2e"]) for r in rows], dtype=float)
    mem = np.asarray([float(r["mem_peak_mb_e2e"]) for r in rows], dtype=float)
    cpu = np.asarray([float(r["cpu_norm_e2e"]) for r in rows], dtype=float)

    fig, axes = plt.subplots(1, 3, figsize=(11.0, 3.4), constrained_layout=True)
    axes[0].bar(x, fps, color="#4C78A8")
    axes[0].set_title(r"FPS$_{\mathrm{e2e}}$")
    axes[0].set_ylabel("frames/s")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(methods, rotation=15)
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(x, mem, color="#F58518")
    axes[1].set_title(r"Mem$_{\mathrm{peak}}$")
    axes[1].set_ylabel("MB")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(methods, rotation=15)
    axes[1].grid(axis="y", alpha=0.25)

    axes[2].bar(x, cpu, color="#54A24B")
    axes[2].set_title(r"CPU$_{\mathrm{norm}}$")
    axes[2].set_ylabel("ratio")
    axes[2].set_xticks(x)
    axes[2].set_xticklabels(methods, rotation=15)
    axes[2].grid(axis="y", alpha=0.25)

    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, **PLOT_SAVE_KWARGS)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    rows = read_rows(args.in_csv)
    summary_rows = write_summary(args.summary_csv, rows)
    write_table(args.table_tex, summary_rows)
    write_figure(args.fig_pdf, summary_rows)
    print(f"wrote summary: {args.summary_csv}")
    print(f"wrote table:   {args.table_tex}")
    print(f"wrote figure:  {args.fig_pdf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
