#!/usr/bin/env python
"""Generate bucket-shift LaTeX table from exported BrackishMOT CSV."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import numpy as np
import pandas as pd


BUCKET_ORDER = ["occlusion", "density", "turning", "low-confidence"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build bucket_shift_table.tex from brackishmot_bucket_shift.csv.")
    parser.add_argument(
        "--in-csv",
        type=Path,
        default=Path("results/brackishmot_bucket_shift.csv"),
    )
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=Path("paper/cea_draft/tables/bucket_shift_table.tex"),
    )
    return parser.parse_args()


def _fmt(v: float) -> str:
    if np.isnan(v):
        return "NA"
    return f"{v:+.3f}"


def main() -> int:
    args = parse_args()
    if not args.in_csv.exists():
        raise FileNotFoundError(f"Missing input CSV: {args.in_csv}")
    df = pd.read_csv(args.in_csv)
    sub = df[(df["method"] == "+gating") & (df["group"].isin(["high", "turbid_high"]))].copy()
    if sub.empty:
        # strict to expected naming used in this repository
        sub = df[(df["method"] == "+gating") & (df["group"] == "turbid_high")].copy()

    lines: List[str] = [
        "% Auto-generated by scripts/make_bucket_shift_table.py",
        r"\begin{tabular}{lll}",
        r"\toprule",
        r"Bucket & $\Delta$IDSW (high stress vs clean) & Note \\",
        r"\midrule",
    ]

    for bucket in BUCKET_ORDER:
        row = sub[sub["bucket_name"] == bucket]
        if row.empty:
            lines.append(f"{bucket} & NA & not observed \\\\")
            continue
        rec = row.iloc[0]
        d_idsw = float(rec["delta_idsw"]) if "delta_idsw" in rec else np.nan
        raw_note = rec.get("note", "")
        note = "" if pd.isna(raw_note) else str(raw_note).strip()
        if not note:
            note = "ok"
        lines.append(f"{bucket} & {_fmt(d_idsw)} & {note} \\\\")

    lines.extend([r"\bottomrule", r"\end{tabular}"])
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote bucket table: {args.out_tex}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
