#!/usr/bin/env python
"""Build Brackish Scope-B table and optional figure from summary CSV."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


SCENARIO_ORDER = ["clear", "turbid_high", "turbid_low"]
METHOD_ORDER = ["Base", "+gating", "+traj", "+adaptive"]

PLOT_STYLE = {
    "font.family": "Times New Roman",
    "font.size": 10,
    "axes.titlesize": 10,
    "axes.labelsize": 10,
    "xtick.labelsize": 8,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "axes.linewidth": 0.8,
    "grid.linewidth": 0.4,
}
PLOT_SAVE_KWARGS = {"dpi": 300, "bbox_inches": "tight", "pad_inches": 0.02}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate runtime_scopeb_brackish.tex from summary CSV.")
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("results/brackishmot/runtime/runtime_profile_e2e_summary.csv"),
    )
    parser.add_argument(
        "--table-tex",
        type=Path,
        default=Path("paper/cea_draft/tables/runtime_scopeb_brackish.tex"),
    )
    parser.add_argument(
        "--fig-pdf",
        type=Path,
        default=Path("paper/cea_draft/figures/runtime_e2e_brackish_bar.pdf"),
    )
    return parser.parse_args()


def _pm(mean_v: float, std_v: float, d: int = 3) -> str:
    return f"{mean_v:.{d}f} $\\pm$ {std_v:.{d}f}"


def _scenario_sort_key(name: str) -> int:
    if name in SCENARIO_ORDER:
        return SCENARIO_ORDER.index(name)
    return len(SCENARIO_ORDER) + 1


def _method_sort_key(name: str) -> int:
    if name in METHOD_ORDER:
        return METHOD_ORDER.index(name)
    return len(METHOD_ORDER) + 1


def write_table(path: Path, df: pd.DataFrame) -> None:
    rows = df.sort_values(
        by=["scenario", "method"],
        key=lambda s: s.map(_scenario_sort_key) if s.name == "scenario" else s.map(_method_sort_key),
    )
    lines: List[str] = [
        "% Auto-generated by scripts/make_scopeb_table.py",
        r"\begin{tabular}{lllllllllll}",
        r"\toprule",
        r"Scenario & Method & fps\_e2e & mem\_peak\_mb\_e2e & cpu\_norm\_e2e & decode\_time & detector\_time & tracking\_time & write\_time & detector\_name & input\_resolution \\",
        r"\midrule",
    ]
    for _, r in rows.iterrows():
        lines.append(
            " & ".join(
                [
                    str(r["scenario"]),
                    str(r["method"]),
                    _pm(float(r["fps_e2e"]), float(r["fps_e2e_std"]), d=3),
                    _pm(float(r["mem_peak_mb_e2e"]), float(r["mem_peak_mb_e2e_std"]), d=3),
                    _pm(float(r["cpu_norm_e2e"]), float(r["cpu_norm_e2e_std"]), d=3),
                    _pm(float(r["decode_time"]), float(r["decode_time_std"]), d=3),
                    _pm(float(r["detector_time"]), float(r["detector_time_std"]), d=3),
                    _pm(float(r["tracking_time"]), float(r["tracking_time_std"]), d=3),
                    _pm(float(r["write_time"]), float(r["write_time_std"]), d=3),
                    str(r["detector_name"]).replace("_", r"\_"),
                    str(r["input_resolution"]).replace("_", r"\_"),
                ]
            )
            + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def write_figure(path: Path, df: pd.DataFrame) -> None:
    plt.rcParams.update(PLOT_STYLE)
    plot_df = df.copy()
    plot_df["scenario_method"] = plot_df["scenario"] + "-" + plot_df["method"]
    x = np.arange(len(plot_df), dtype=float)
    fps = plot_df["fps_e2e"].to_numpy(dtype=float)
    mem = plot_df["mem_peak_mb_e2e"].to_numpy(dtype=float)
    cpu = plot_df["cpu_norm_e2e"].to_numpy(dtype=float)

    fig, axes = plt.subplots(1, 3, figsize=(11.0, 3.6), constrained_layout=True)
    axes[0].bar(x, fps, color="#4C78A8")
    axes[0].set_title(r"fps\_e2e")
    axes[0].set_ylabel("frames/s")
    axes[0].set_xticks(x)
    axes[0].set_xticklabels(plot_df["scenario_method"], rotation=25, ha="right")
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(x, mem, color="#F58518")
    axes[1].set_title(r"mem\_peak\_mb\_e2e")
    axes[1].set_ylabel("MB")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(plot_df["scenario_method"], rotation=25, ha="right")
    axes[1].grid(axis="y", alpha=0.25)

    axes[2].bar(x, cpu, color="#54A24B")
    axes[2].set_title(r"cpu\_norm\_e2e")
    axes[2].set_ylabel("ratio")
    axes[2].set_xticks(x)
    axes[2].set_xticklabels(plot_df["scenario_method"], rotation=25, ha="right")
    axes[2].grid(axis="y", alpha=0.25)

    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, **PLOT_SAVE_KWARGS)
    plt.close(fig)


def main() -> int:
    args = parse_args()
    if not args.summary_csv.exists():
        raise FileNotFoundError(f"Missing summary CSV: {args.summary_csv}")
    df = pd.read_csv(args.summary_csv)
    need = {
        "scenario",
        "method",
        "fps_e2e",
        "fps_e2e_std",
        "mem_peak_mb_e2e",
        "mem_peak_mb_e2e_std",
        "cpu_norm_e2e",
        "cpu_norm_e2e_std",
        "decode_time",
        "decode_time_std",
        "detector_time",
        "detector_time_std",
        "tracking_time",
        "tracking_time_std",
        "write_time",
        "write_time_std",
        "detector_name",
        "input_resolution",
    }
    miss = sorted(need - set(df.columns))
    if miss:
        raise ValueError(f"Summary CSV missing columns: {miss}")

    write_table(args.table_tex, df)
    write_figure(args.fig_pdf, df)
    print(f"wrote table: {args.table_tex}")
    print(f"wrote figure: {args.fig_pdf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
