#!/usr/bin/env python
"""Generate paper table snippets from CSV outputs."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, List, Tuple

from method_labels import MAIN_CHAIN_METHOD_ORDER, normalize_main_chain_label


METHOD_ORDER = MAIN_CHAIN_METHOD_ORDER
STRONG_ORDER = ["ByteTrack", "OC-SORT", "BoT-SORT"]
ALL_ORDER = METHOD_ORDER + STRONG_ORDER


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build LaTeX tables from CSV outputs.")
    parser.add_argument("--main-mean", type=Path, default=Path("results/main_val/tables/main_table_val_seedmean.csv"))
    parser.add_argument("--main-std", type=Path, default=Path("results/main_val/tables/main_table_val_seedstd.csv"))
    parser.add_argument(
        "--strong-mean",
        type=Path,
        default=Path("results/main_val/tables/strong_baselines_seedmean.csv"),
    )
    parser.add_argument(
        "--strong-std",
        type=Path,
        default=Path("results/main_val/tables/strong_baselines_seedstd.csv"),
    )
    parser.add_argument(
        "--all-methods",
        type=Path,
        default=Path("results/main_val/tables/main_table_val_with_baselines.csv"),
    )
    parser.add_argument(
        "--count-csv",
        type=Path,
        default=Path("results/main_val/tables/count_metrics_val.csv"),
    )
    parser.add_argument(
        "--gating-csv",
        type=Path,
        default=Path("results/main_val/tables/gating_thresh_sensitivity.csv"),
    )
    parser.add_argument(
        "--degradation-csv",
        type=Path,
        default=Path("results/main_val/tables/degradation_grid.csv"),
    )
    parser.add_argument("--stress-params-csv", type=Path, default=Path("results/stress_params.csv"))
    parser.add_argument("--scopeb-csv", type=Path, default=Path("results/main_val/runtime/scopeb_profile.csv"))
    parser.add_argument("--gating-trigger-csv", type=Path, default=Path("results/gating/trigger_rate_table.csv"))
    parser.add_argument("--out-dir", type=Path, default=Path("paper/cea_draft/tables"))
    return parser.parse_args()


def read_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"CSV not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def fmt_uncertainty(mean_s: str, std_s: str, decimals: int = 3) -> str:
    mean = float(mean_s)
    std = float(std_s)
    scaled_std = int(round(abs(std) * (10**decimals)))
    return f"{mean:.{decimals}f}({scaled_std})"


def write_lines(path: Path, lines: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def build_core_table(main_mean: List[Dict[str, str]], main_std: List[Dict[str, str]], out_path: Path) -> None:
    mean_map = {normalize_main_chain_label(r["method"]): {**r, "method": normalize_main_chain_label(r["method"])} for r in main_mean}
    std_map = {normalize_main_chain_label(r["method"]): {**r, "method": normalize_main_chain_label(r["method"])} for r in main_std}
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from main_table_val_seedmean/std.csv",
        r"\begin{tabular}{l S S S S S}",
        r"\toprule",
        r"Method & {HOTA} & {DetA} & {AssA} & {IDF1} & {IDSW} \\",
        r"\midrule",
    ]
    for method in METHOD_ORDER:
        m = mean_map[method]
        s = std_map[method]
        cells = [method] + [fmt_uncertainty(m[k], s[k]) for k in ["HOTA", "DetA", "AssA", "IDF1", "IDSW"]]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_strong_table(strong_mean: List[Dict[str, str]], strong_std: List[Dict[str, str]], out_path: Path) -> None:
    mean_map = {r["method"]: r for r in strong_mean}
    std_map = {r["method"]: r for r in strong_std}
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from strong_baselines_seedmean/std.csv",
        r"\begin{tabular}{l S S S S S}",
        r"\toprule",
        r"Method & {HOTA} & {DetA} & {AssA} & {IDF1} & {IDSW} \\",
        r"\midrule",
    ]
    for method in STRONG_ORDER:
        m = mean_map[method]
        s = std_map[method]
        cells = [method] + [fmt_uncertainty(m[k], s[k]) for k in ["HOTA", "DetA", "AssA", "IDF1", "IDSW"]]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_all_methods_table(all_rows: List[Dict[str, str]], out_path: Path) -> None:
    row_map = {normalize_main_chain_label(r["method"]): {**r, "method": normalize_main_chain_label(r["method"])} for r in all_rows}
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from main_table_val_with_baselines.csv",
        r"\begin{tabular}{l S S S S S}",
        r"\toprule",
        r"Method & {HOTA} & {DetA} & {AssA} & {IDF1} & {IDSW} \\",
        r"\midrule",
    ]
    for method in ALL_ORDER:
        r = row_map[method]
        cells = [
            method,
            fmt_uncertainty(r["HOTA_mean"], r["HOTA_std"]),
            fmt_uncertainty(r["DetA_mean"], r["DetA_std"]),
            fmt_uncertainty(r["AssA_mean"], r["AssA_std"]),
            fmt_uncertainty(r["IDF1_mean"], r["IDF1_std"]),
            fmt_uncertainty(r["IDSW_mean"], r["IDSW_std"]),
        ]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_count_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    mean_rows = [r for r in rows if r.get("row_type") == "mean"]
    row_map = {normalize_main_chain_label(r["method"]): {**r, "method": normalize_main_chain_label(r["method"])} for r in mean_rows}
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from count_metrics_val.csv",
        r"\begin{tabular}{l S S S S}",
        r"\toprule",
        r"Method & {CountMAE} & {CountRMSE} & {CountVar} & {CountDrift} \\",
        r"\midrule",
    ]
    for method in METHOD_ORDER:
        r = row_map[method]
        cells = [method, f"{float(r['CountMAE']):.3f}", f"{float(r['CountRMSE']):.3f}", f"{float(r['CountVar']):.3f}", f"{float(r['CountDrift']):.3f}"]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_gating_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    base_rows = [r for r in rows if r["method"] == "Base"]
    gating_rows = sorted(
        [r for r in rows if r["method"] == "+gating"],
        key=lambda r: float(r["gating_thresh"]),
    )
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from gating_thresh_sensitivity.csv",
        r"\begin{tabular}{l l S S S S S}",
        r"\toprule",
        r"Method & Gating threshold & {HOTA} & {DetA} & {AssA} & {IDF1} & {IDSW} \\",
        r"\midrule",
    ]
    for r in base_rows + gating_rows:
        g = r["gating_thresh"]
        cells = [
            r["method"],
            g,
            f"{float(r['HOTA']):.3f}",
            f"{float(r['DetA']):.3f}",
            f"{float(r['AssA']):.3f}",
            f"{float(r['IDF1']):.3f}",
            f"{float(r['IDSW']):.3f}",
        ]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def pretty_stress_cell(degradation: str, params_json: str) -> str:
    params = json.loads(params_json)
    if degradation == "motion_blur":
        return (
            f"$\\ell={int(params['kernel_len_px'])}$ px, "
            f"$\\theta={int(params['angle_deg'])}^\\circ$; "
            f"proxy $(p_\\mathrm{{drop}}={params['drop_rate']:.2f},\\ j_\\mathrm{{bbox}}={params['jitter']:.3f})$"
        )
    if degradation == "low_light":
        return (
            f"$\\alpha={params['alpha']:.2f},\\ \\beta={params['beta']:.0f}$; "
            f"proxy $(p_\\mathrm{{drop}}={params['drop_rate']:.2f},\\ j_\\mathrm{{bbox}}={params['jitter']:.3f})$"
        )
    return (
        f"$t={params['t']:.2f},\\ A={params['A']:.2f}$; "
        f"proxy $(p_\\mathrm{{drop}}={params['drop_rate']:.2f},\\ j_\\mathrm{{bbox}}={params['jitter']:.3f})$"
    )


def build_stress_param_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    order = {"motion_blur": 0, "low_light": 1, "turbidity_haze": 2}
    lvl_order = {"low": 0, "mid": 1, "high": 2}
    rows = sorted(rows, key=lambda r: (order[r["degradation"]], lvl_order[r["level"]]))
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from stress_params.csv",
        r"\begin{tabular}{lll}",
        r"\toprule",
        r"Degradation & Strength level & Parameter setting \\",
        r"\midrule",
    ]
    for r in rows:
        pretty = r["degradation"].replace("_", " ").title()
        lines.append(f"{pretty} & {r['level']} & {pretty_stress_cell(r['degradation'], r['params_json'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_degradation_delta_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    key = {}
    for r in rows:
        k = (r["method"], f"{float(r['jitter']):.2f}", f"{float(r['drop_rate']):.2f}")
        key[k] = r

    def delta(method: str, jitter: str, metric: str) -> float:
        low = float(key[(method, jitter, "0.00")][metric])
        high = float(key[(method, jitter, "0.40")][metric])
        return low - high

    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from degradation_grid.csv",
        r"\begin{tabular}{l S S S S S S}",
        r"\toprule",
        r"Jitter & {Base $\Delta$HOTA} & {Base $\Delta$IDF1} & {+gating $\Delta$HOTA} & {+gating $\Delta$IDF1} & {ByteTrack $\Delta$HOTA} & {ByteTrack $\Delta$IDF1} \\",
        r"\midrule",
    ]
    for jitter in ["0.00", "0.02"]:
        vals = [
            f"{delta('Base', jitter, 'HOTA'):.3f}",
            f"{delta('Base', jitter, 'IDF1'):.3f}",
            f"{delta('+gating', jitter, 'HOTA'):.3f}",
            f"{delta('+gating', jitter, 'IDF1'):.3f}",
            f"{delta('ByteTrack', jitter, 'HOTA'):.3f}",
            f"{delta('ByteTrack', jitter, 'IDF1'):.3f}",
        ]
        lines.append(" & ".join([jitter] + vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_scopeb_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    mean_rows = [r for r in rows if r.get("row_type", "").lower() == "mean"]
    row_map = {normalize_main_chain_label(r["method"]): {**r, "method": normalize_main_chain_label(r["method"])} for r in mean_rows}
    method_order = METHOD_ORDER
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from scopeb_profile.csv",
        r"\begin{tabular}{l S S S S S S}",
        r"\toprule",
        r"Method & {FPS$_{\mathrm{e2e}}$} & {Mem$_{\mathrm{peak}}$ (MB)} & {CPU$_{\mathrm{norm}}$} & {Decode (s)} & {Detector (s)} & {Track+Write (s)} \\",
        r"\midrule",
    ]
    for method in method_order:
        if method not in row_map:
            continue
        r = row_map[method]
        trk_write = float(r["tracking_time"]) + float(r["write_time"])
        lines.append(
            " & ".join(
                [
                    method,
                    f"{float(r['fps_e2e']):.3f}({int(round(float(r.get('fps_e2e_std', '0')) * 1000))})",
                    f"{float(r['mem_peak_mb_e2e']):.3f}({int(round(float(r.get('mem_peak_mb_e2e_std', '0')) * 1000))})",
                    f"{float(r['cpu_norm_e2e']):.3f}({int(round(float(r.get('cpu_norm_e2e_std', '0')) * 1000))})",
                    f"{float(r['decode_time']):.3f}",
                    f"{float(r['detector_time']):.3f}",
                    f"{trk_write:.3f}",
                ]
            )
            + r" \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def build_gating_trigger_table(rows: List[Dict[str, str]], out_path: Path) -> None:
    rows = sorted(rows, key=lambda r: float(r["threshold"]))
    lines = [
        "% Auto-generated by scripts/make_paper_tables.py from trigger_rate_table.csv",
        r"\begin{tabular}{S S S S}",
        r"\toprule",
        r"{\tau_g} & {Frame trigger rate} & {Sequence trigger rate} & {Masked-pair rate} \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            " & ".join(
                [
                    f"{float(r['threshold']):.0f}",
                    f"{float(r['trigger_rate_frame']):.6f}",
                    f"{float(r['trigger_rate_sequence']):.6f}",
                    f"{float(r.get('masked_pair_rate', 0.0)):.6f}",
                ]
            )
            + r" \\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_lines(out_path, lines)


def main() -> int:
    args = parse_args()
    main_mean = read_rows(args.main_mean)
    main_std = read_rows(args.main_std)
    strong_mean = read_rows(args.strong_mean)
    strong_std = read_rows(args.strong_std)
    all_methods = read_rows(args.all_methods)
    count_rows = read_rows(args.count_csv)
    gating_rows = read_rows(args.gating_csv)
    degrid_rows = read_rows(args.degradation_csv)
    stress_rows = read_rows(args.stress_params_csv)
    scopeb_rows: List[Dict[str, str]] = []
    if args.scopeb_csv.exists():
        scopeb_rows = read_rows(args.scopeb_csv)
    gating_trigger_rows: List[Dict[str, str]] = []
    if args.gating_trigger_csv.exists():
        gating_trigger_rows = read_rows(args.gating_trigger_csv)

    build_core_table(main_mean, main_std, args.out_dir / "paper_main_table.tex")
    build_strong_table(strong_mean, strong_std, args.out_dir / "strong_baselines_seedmean_std.tex")
    build_all_methods_table(all_methods, args.out_dir / "main_table_with_baselines.tex")
    build_count_table(count_rows, args.out_dir / "paper_count_table.tex")
    build_gating_table(gating_rows, args.out_dir / "gating_sensitivity.tex")
    build_stress_param_table(stress_rows, args.out_dir / "stress_param_table.tex")
    build_degradation_delta_table(degrid_rows, args.out_dir / "degradation_delta.tex")
    if scopeb_rows:
        build_scopeb_table(scopeb_rows, args.out_dir / "scopeb_runtime.tex")
    if gating_trigger_rows:
        build_gating_trigger_table(gating_trigger_rows, args.out_dir / "gating_trigger_rates.tex")

    print(f"Generated table snippets in: {args.out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
